#!/usr/bin/python
# coding:utf-8

TIME_FORMAT = '%Y%m%d%H%M'
DATE_FORMAT = '%Y%m%d'

SQL_COL_SEPARTOR = ','
SQL_INSERT_INTO = 'INSERT INTO %s(%s) VALUES (%s)'

QUERY_INDEX_STOCK_BASIC = 1
QUERY_INDEX_TRADE_CAL = 2
QUERY_INDEX_STOCK_COMPANY = 3
QUERY_INDEX_NAMECHANGE = 4
