#!/usr/bin/python
# coding:utf-8

TIME_FORMAT = '%Y%m%d%H%M'
DATE_FORMAT = '%Y%m%d'

SQL_COL_SEPARTOR = ','
SQL_INSERT_INTO = 'INSERT INTO %s(%s) VALUES (%s)'

COL_TYPE_STR = 'str'
COL_TYPE_INT = 'int'
COL_TYPE_FLOAT = 'float'

COL_TS_CODE = 'ts_code'
COL_SYMBOL = 'symbol'
COL_NAME = 'name'
COL_AREA = 'area'
COL_INDUSTRY = 'industry'
COL_FULLNAME = 'fullname'
COL_ENNAME = 'enname'
COL_MARKET = 'market'
COL_EXCHANGE = 'exchange'
COL_CURR_TYPE = 'curr_type'
COL_LIST_STATUS = 'list_status'
COL_LIST_DATE = 'list_date'
COL_DELIST_DATE = 'delist_date'
COL_IS_HS = 'is_hs'

QUERY_INDEX_STOCK_BASIC = 1

TABLE_STOCK_BASIC = 'stock_basic'
STOCK_BASIC_COL_ALL = [COL_TS_CODE, COL_SYMBOL, COL_NAME, COL_AREA, COL_INDUSTRY, COL_FULLNAME, COL_ENNAME, COL_MARKET, COL_EXCHANGE, COL_CURR_TYPE, COL_LIST_STATUS, COL_LIST_DATE, COL_DELIST_DATE, COL_IS_HS]
STOCK_BASIC_COL_TYPE = [COL_TYPE_STR, COL_TYPE_STR, COL_TYPE_STR, COL_TYPE_STR, COL_TYPE_STR, COL_TYPE_STR, COL_TYPE_STR, COL_TYPE_STR, COL_TYPE_STR, COL_TYPE_STR, COL_TYPE_STR, COL_TYPE_STR, COL_TYPE_STR, COL_TYPE_STR]
