#!/usr/bin/python
# coding:utf-8

SQL_COL_SEPARTOR = ','
SQL_INSERT_INTO = 'INSERT INTO %s(%s) VALUES (%s)'

COL_TYPE_STR = 'str'
COL_TYPE_INT = 'int'
COL_TYPE_FLOAT = 'float'

COL_TS_CODE = 'ts_code'
COL_SYMBOL = 'symbol'
COL_NAME = 'name'
COL_AREA = 'area'
COL_INDUSTRY = 'industry'
COL_FULLNAME = 'fullname'
COL_ENNAME = 'enname'
COL_MARKET = 'market'
COL_EXCHANGE = 'exchange'
COL_CURR_TYPE = 'curr_type'
COL_LIST_STATUS = 'list_status'
COL_LIST_DATE = 'list_date'
COL_DELIST_DATE = 'delist_date'
COL_IS_HS = 'is_hs'
COL_CAL_DATE = 'cal_date'
COL_IS_OPEN = 'is_open'
COL_PRETRADE_DATE = 'pretrade_date'
COL_CHAIRMAN = 'chairman'
COL_MANAGER = 'manager'
COL_SECRETARY = 'secretary'
COL_REG_CAPITAL = 'reg_capital'
COL_SETUP_DATE = 'setup_date'
COL_PROVINCE = 'province'
COL_CITY = 'city'
COL_INTRODUCTION = 'introduction'
COL_WEBSITE = 'website'
COL_EMAIL = 'email'
COL_OFFICE = 'office'
COL_EMPLOYEES = 'employees'
COL_MAIN_BUSINESS = 'main_business'
COL_BUSINESS_SCOPE = 'business_scope'
COL_START_DATE = 'start_date'
COL_END_DATE = 'end_date'
COL_ANN_DATE = 'ann_date'
COL_CHANGE_REASON = 'change_reason'

# 股票列表
# 描述：获取基础信息数据，包括股票代码、名称、上市日期、退市日期等
TABLE_STOCK_BASIC = 'stock_basic'
STOCK_BASIC_COL_ALL = [COL_TS_CODE, COL_SYMBOL, COL_NAME, COL_AREA, COL_INDUSTRY, COL_FULLNAME, COL_ENNAME, COL_MARKET, COL_EXCHANGE, COL_CURR_TYPE, COL_LIST_STATUS, COL_LIST_DATE, COL_DELIST_DATE, COL_IS_HS]
STOCK_BASIC_COL_TYPE = [COL_TYPE_STR, COL_TYPE_STR, COL_TYPE_STR, COL_TYPE_STR, COL_TYPE_STR, COL_TYPE_STR, COL_TYPE_STR, COL_TYPE_STR, COL_TYPE_STR, COL_TYPE_STR, COL_TYPE_STR, COL_TYPE_STR, COL_TYPE_STR, COL_TYPE_STR]

# 交易日历
# 描述：获取各大交易所交易日历数据,默认提取的是上交所
TABLE_TRADE_CAL = 'trade_cal'
TRADE_CAL_COL_ALL = [COL_EXCHANGE, COL_CAL_DATE, COL_IS_OPEN, COL_PRETRADE_DATE]
TRADE_CAL_COL_TYPE = [COL_TYPE_STR, COL_TYPE_STR, COL_TYPE_INT, COL_TYPE_STR]

# 上市公司基本信息
# 描述：获取上市公司基础信息
TABLE_STOCK_COMPANY = 'stock_company'
ALL_COL_STOCK_COMPANY = [COL_TS_CODE, COL_EXCHANGE, COL_CHAIRMAN, COL_MANAGER, COL_SECRETARY, COL_REG_CAPITAL, COL_SETUP_DATE, COL_PROVINCE, COL_CITY, COL_INTRODUCTION, COL_WEBSITE, COL_EMAIL, COL_OFFICE, COL_MAIN_BUSINESS, COL_EMPLOYEES, COL_BUSINESS_SCOPE]
ALL_TYPE_STOCK_COMPANY = [COL_TYPE_STR, COL_TYPE_STR, COL_TYPE_STR, COL_TYPE_STR, COL_TYPE_STR, COL_TYPE_FLOAT, COL_TYPE_STR, COL_TYPE_STR, COL_TYPE_STR, COL_TYPE_STR, COL_TYPE_STR, COL_TYPE_STR, COL_TYPE_STR, COL_TYPE_STR, COL_TYPE_INT, COL_TYPE_STR]

# 股票曾用名
# 描述：历史名称变更记录
TABLE_NAMECHANGE = 'namechange'
ALL_COL_NAMECHANGE = [COL_TS_CODE, COL_NAME, COL_START_DATE, COL_END_DATE, COL_ANN_DATE, COL_CHANGE_REASON]
ALL_TYPE_NAMECHANGE = [COL_TYPE_STR, COL_TYPE_STR, COL_TYPE_STR, COL_TYPE_STR, COL_TYPE_STR, COL_TYPE_STR]
